name: AI Code Review

on:
  pull_request:
    types: [opened, closed]

permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: AI Code Review
        uses: villesau/ai-codereviewer@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_MODEL: "gpt-4"
          