
name: CI Workflow

on:
  push:
    branches: [main]
  #pull_request:
    # types: [opened, closed]
  #schedule:
    # - cron: '*/3 * * * *'  # Runs every 3 minutes
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build Project

        run: echo "Building proyect...."
