
name: CI Workflow

on: 
    #pull_request:
     # types: [opened, closed]
     #schedule:
      # - cron: '*/3 * * * *'  # Runs every 3 minutes
    branches: [develop]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build Project

        run: echo "Building proyect...."
