name: CI WorkFlow

on:
    push:
      branches:
        - develop
  
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v5
          #run: |
          #  git init
          #  git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          #  git fetch origin ${{ github.ref }} --depth=1
          #  git checkout FETCH_HEAD
          #  ls -la
        - name: Install dependencies
          uses: actions/setup-python@v4
          #run: |
          #  echo "Installing dependencies...."
          #  echo "status=sucess" >> $GITHUB_OUTPUT
          id: step1
          #run: |
          #  print("Installing dependencies....")
          #  print("Running tests....")
          #shell: python
        - name: Run Tests
          if: ${{ steps.step1.outputs.status == 'sucess' }}
          run: |
            echo "El resultado del paso anterior fue ${{ steps.step1.outputs.status }}"
            echo "Running tests...."
          shell: bash