name: CI WorkFlow

on:
    push:
      branches:
        - develop
  
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Test Project
          run: |
            print("Installing dependencies....")
            print("Running tests....")
          shell: python