name: CI Workflow
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  repository_dispatch:
    types: [test-event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutBuild
        run: echo "Building..."
