
name: CI Workflow


on: 
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
     - main

     #schedule:
      #- cron: '*/3 * * * *'  # Runs every 3 minutes  
    #pull_request:
     # types: [opened, closed]
     #schedule:
      #- cron: '*/3 * * * *'  # Runs every 3 minutes

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build Project

        run: echo "Building proyect...."
