
name: CI Workflow

on: 
    pull_request:
      types: [opened, closed]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build Project

        run: echo "Building proyect...."
