name: Hello World workflow
on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run hello script
        run: python3 main.py

  test:
    runs-on: ubuntu-latest
    #needs: hello
    #if: ${{ needs.hello.result == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: echo "Deploying..."
